/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.caralarm;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;

/**
 *
 * @author Ramon
 */
public class CarSimulator extends javax.swing.JFrame {

    /**
     * Creates new form CarSimulator
     */
    public CarSimulator() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bdoor1 = new javax.swing.JToggleButton();
        bdoor2 = new javax.swing.JToggleButton();
        bdoor3 = new javax.swing.JToggleButton();
        bdoor4 = new javax.swing.JToggleButton();
        bbonnet = new javax.swing.JToggleButton();
        binside = new javax.swing.JToggleButton();
        bfuel = new javax.swing.JToggleButton();
        bboot = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        talarma = new javax.swing.JTextField();
        bgasMode = new javax.swing.JToggleButton();
        bfullMode = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Alarm - simulator");
        setResizable(false);

        bdoor1.setText("Door");
        bdoor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdoor1ActionPerformed(evt);
            }
        });

        bdoor2.setText("Door");
        bdoor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdoor2ActionPerformed(evt);
            }
        });

        bdoor3.setText("Door");
        bdoor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdoor3ActionPerformed(evt);
            }
        });

        bdoor4.setText("Door");
        bdoor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdoor4ActionPerformed(evt);
            }
        });

        bbonnet.setText("Bonnet");
        bbonnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbonnetActionPerformed(evt);
            }
        });

        binside.setText("Inside");

        bfuel.setText("Fuel");
        bfuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfuelActionPerformed(evt);
            }
        });

        bboot.setText("Boot");
        bboot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbootActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bgasMode.setSelected(true);
        bgasMode.setText("Gas mode");
        bgasMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgasModeActionPerformed(evt);
            }
        });

        bfullMode.setText("Full Mode");
        bfullMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfullModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bfuel)
                    .addComponent(bboot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdoor4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdoor2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(binside, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbonnet)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bgasMode)
                        .addGap(18, 18, 18)
                        .addComponent(bfullMode)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(talarma, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(talarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdoor4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdoor1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bboot, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binside, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbonnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bdoor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bfuel)
                    .addComponent(bdoor3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bfullMode)
                    .addComponent(bgasMode))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bbonnet, bboot});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.talarma.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bdoor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdoor1ActionPerformed
        this.check();
    }//GEN-LAST:event_bdoor1ActionPerformed

    private void bfuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfuelActionPerformed
        this.check();
    }//GEN-LAST:event_bfuelActionPerformed

    private void bdoor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdoor2ActionPerformed
        this.check();
    }//GEN-LAST:event_bdoor2ActionPerformed

    private void bdoor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdoor3ActionPerformed
        this.check();        // TODO add your handling code here:
    }//GEN-LAST:event_bdoor3ActionPerformed

    private void bdoor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdoor4ActionPerformed
        this.check();
    }//GEN-LAST:event_bdoor4ActionPerformed

    private void bgasModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgasModeActionPerformed
        talarma.setText("Alarm in Gas Mode ");
    }//GEN-LAST:event_bgasModeActionPerformed

    private void bbootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbootActionPerformed
        this.check();
    }//GEN-LAST:event_bbootActionPerformed

    private void bbonnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbonnetActionPerformed
        this.check();
    }//GEN-LAST:event_bbonnetActionPerformed

    private void bfullModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfullModeActionPerformed
        
        
        
        new Thread(() -> {
            try {
                if(!bfullMode.isSelected())
                {
                    repaint();
                    talarma.setText("Alarm dissarmed");
                    repaint();
                }
                else
                {
                    for(int i=0;i<10;i++)
                    {
                        repaint();
                        talarma.setText("Mounting alarm in Full Mode ");
                        Thread.sleep(1000);
                        talarma.setText("");
                        Thread.sleep(500);
                        repaint();
                    }
                    
                    
                    talarma.setText("Alarm mounted in Full Mode");
                    repaint();
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(CarSimulator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();

        
        
        
    }//GEN-LAST:event_bfullModeActionPerformed

    private boolean check()
    {
        boolean sw=false;
        if(bgasMode.isSelected())
        {
            if(bfuel.isSelected()&& (bdoor1.isSelected()||bdoor2.isSelected()||bdoor3.isSelected()||bdoor4.isSelected()||bbonnet.isSelected()||bboot.isSelected()))
            {
                talarma.setText("Alarm sounding - Gas mode");
                sw=true;
            }
            else
            {
                sw=false;
            }
        }
        if(bfullMode.isSelected())
        {
            if(bfuel.isSelected() || bdoor1.isSelected()||bdoor2.isSelected()||bdoor3.isSelected()||bdoor4.isSelected()||bbonnet.isSelected()||bboot.isSelected())
            {
                talarma.setText("Alarm sounding - Full mode");
                sw=true;
            }
            else
            {
                sw=false;
            }
        }
        
        
        return sw;
    }
    
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bbonnet;
    private javax.swing.JToggleButton bboot;
    private javax.swing.JToggleButton bdoor1;
    private javax.swing.JToggleButton bdoor2;
    private javax.swing.JToggleButton bdoor3;
    private javax.swing.JToggleButton bdoor4;
    private javax.swing.JToggleButton bfuel;
    private javax.swing.JToggleButton bfullMode;
    private javax.swing.JToggleButton bgasMode;
    private javax.swing.JToggleButton binside;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField talarma;
    // End of variables declaration//GEN-END:variables
}
